### ISSUE TITLE
xk6-kubernetes extension can't be used in-cluster

### ISSUE THREAD

**Issue by JorTurFer** [grafana/xk6-kubernetes#100]
We are using in KEDA this extension to populate k8s resources for the load tests and it worked nice when we executed the tests locally, but when we have tried to move the test from local to k6-operator, we have faced with the problem that the extension can init the Kubernetes client with this error:
```bash
time="2023-08-22T18:39:57Z" level=error msg="GoError: stat /home/k6/.kube/config: no such file or directory
```

I think that this error is because during the extension init, the path is forced to `$HOME/.kube/config` even if I kept it clear intentionally for using in-cluster mode.
https://github.com/grafana/xk6-kubernetes/blob/693426da9079a2edd423e90b2a0135f06ba7173f/kubernetes.go#L147-L157

Managing this at this level doesn't make sense (IMHO) because there is already helper in controller-runtime that allow to read files from kubeconfig (whereas it is) or in-cluster.
https://github.com/kubernetes-sigs/controller-runtime/blob/116a1b831fffe7ccc3c8145306c3e1a3b1b14ffa/alias.go#L84-L97

Just with this small change the extension should work in both cases, outside and inside the cluster.

I'm trying this change with my fork, I can draft a PR if it works and you see this change useful

**Comment by JorTurFer** [comment]
After some tries, that helper doesn't work IDK and I'm a bit lost inside goja to troubleshoot the panic :/ 
nvm, I have modified a bit the current code to check if we are in-cluster if `kubeconfig = ""` and now it's working perfectly. This is my patch:
```golang
func getClientConfig(options KubeConfig) (*rest.Config, error) {
	kubeconfig := options.ConfigPath
	if kubeconfig == "" {
		// are we in-cluster?
		config, err := restclient.InClusterConfig()
		if err == nil {
			return config, nil
		}
		// we aren't in-cluster
		home := homedir.HomeDir()
		if home == "" {
			return nil, errors.New("home directory not found")
		}
		kubeconfig = filepath.Join(home, ".kube", "config")
	}
	return clientcmd.BuildConfigFromFlags("", kubeconfig)
}
```
If it's possible, I'd like to draft a PR fixing this instead of having to fork and maintain the repo from my side. Do you want the PR?
FYI @javaducky 

I can try to go further with the controller-runtime helper if you prefer that approach (but maybe I need some help)

**Comment by javaducky** [comment]
@JorTurFer, please submit a PR with what you've got working. I'll take a look at it as well.

**Comment by JorTurFer** [comment]
> @JorTurFer, please submit a PR with what you've got working. I'll take a look at it as well.

Sure, this is the PR: #101 
It's a really small change, but it allows to run this extension inside the cluster using k6-operator. I had to create all the RBAC stuff obviously, but with this change + RBAC changes, I had been able to run the load tests using k6-operator
