### ISSUE TITLE
`kubernetes.*.get methods` should not throw GoError exceptions when the resource is not available

### ISSUE THREAD

**Issue by ppcano** [grafana/xk6-kubernetes#17]
Each existing module provides a `get` method to return the resource info:

- `deployments.get(name, nameSpace)`
- `config_maps.get(name, nameSpace)`
- `ingresses.get(name, nameSpace)`
- `jobs.get(name, nameSpace)`
- `namespaces.get(name)`
- `pods.get(name, nameSpace)`
- `secrets.get(name, nameSpace)`
- `services.get(name, nameSpace)`

When the resource is not available, the call throws an exception. 

```
ERRO[0000] GoError: deployments.apps "hello-mnikube" not found
	at reflect.methodValueCall (native)
	at file:///Users/ppcano/dev/li/k8s/xk6-kubernetes/examples/get-deployment.js:10:55(15)  executor=per-vu-iterations scenario=default source=stacktrace
```

If the resource is not available, the method should return null.

**Comment by pablochacin** [comment]
These method are going to be deprecated soon. Therefore implementing this change is not required.
