### ISSUE TITLE
support only some specific kubernetes version?

### ISSUE THREAD

**Issue by jsarkar** [grafana/xk6-kubernetes#22]
I am trying to run test with kubernetes version `v1.19.13` using most of example scripts.But I don't think it's working. For an example, 
get-pod.js - when I run it from local and pod not present in namespace,the test should display: `pod not found`

**Comment by javaducky** [comment]
Hi @jsarkar! Sorry for the delay, I hadn't realized this was pending for me 😓. 

Please provide a bit more context. I was able to confirm operation against a local `v1.19.11` cluster. Were you able to build the new k6 binary?

**Comment by javaducky** [comment]
Closing this issue as investigation could not discover an issue and no additional feedback provided.
