### ISSUE TITLE
Feature Request: port-fowarding with kubectl

### ISSUE THREAD

**Issue by kempsterc** [grafana/xk6-kubernetes#23]
### Feature Request

* Is there a way to use this plugin to port-forward?
*  `kubectl port-forward MySQL 3306:3306`

**Comment by javaducky** [comment]
Hello @kempsterc! At the moment, no. I'll take a look to see if that's something we can get incorporated.

**Comment by kempsterc** [comment]
@javaducky missed this comment! Sorry! Thank you for that! 😀
