### ISSUE TITLE
building with make fails because local module is not used

### ISSUE THREAD

**Issue by pablochacin** [grafana/xk6-kubernetes#27]
After forking the repository for adding a new package `nodes`, the `make` command failed because it was still referencing the xk6-kubernetes package from the github repository:

> github.com/grafana/xk6-kubernetes/pkg/nodes: module github.com/grafana/xk6-kubernetes@latest found (v0.0.0-20220330204656-f40616db6d32), but does not contain package github.com/grafana/xk6-kubernetes/pkg/nodes

Removing the `--with` option in the `k6 build` command in the Makefile solves the issue.

```
--- a/Makefile
+++ b/Makefile
@@ -19,7 +19,7 @@ clean:
 ## build: Builds a custom 'k6' with the local extension. 
 build:
        go install go.k6.io/xk6/cmd/xk6@latest
-       xk6 build --with github.com/grafana/xk6-output-prometheus-remote=.
+       xk6 build
```

This behavior is unexpected as `xk6` [should add the current module to the list of replaced modules.](https://github.com/grafana/xk6/blob/master/cmd/xk6/main.go#L185-L207)

**Comment by ppcano** [comment]
cc @javaducky
