### ISSUE TITLE
jobs.create: check the successful execution 

### ISSUE THREAD

**Issue by ppcano** [grafana/xk6-kubernetes#37]
**Problem**

At this moment, `jobs.create` does not guarantee a command is properly executed on a node. 

**Case 1**: Given a wrong image name `busybo`.

```javascript
import { sleep } from 'k6';
import { Kubernetes } from 'k6/x/kubernetes';

export default function () {

  const k = new Kubernetes({});

  k.jobs.create({
    namespace: 'default',
    node_name: 'minikube',
    name: 'my-new-job3',
    image: 'busybo',
    command: ["sh", "-c", "sleep 20"]
  });

  sleep(10);
```

It will fail.

<img width="1370" alt="Screenshot 2022-04-26 at 18 13 33" src="https://user-images.githubusercontent.com/825430/165345470-9a48a160-6066-4546-ad16-f6059d9b5ca6.png">

The error is muted and not propagated to the k6 code.

**Case 2** - Given a wrong command name `sherror`:

```javascript
import { sleep } from 'k6';
import { Kubernetes } from 'k6/x/kubernetes';

export default function () {

  const k = new Kubernetes({});

  k.jobs.create({
    namespace: 'default',
    node_name: 'minikube',
    name: 'my-new-job3',
    image: 'busybox',
    command: ["sherror", "-c", "sleep 20"]
  });

  sleep(10);
```

It will fail.

<img width="1391" alt="Screenshot 2022-04-26 at 18 19 21" src="https://user-images.githubusercontent.com/825430/165346529-2e522634-d514-4ee6-b2c1-8913adfe4c3a.png">

The error is muted and not propagated to the k6 code.

**Case 3** - Given a wrong `node_name`

<img width="1443" alt="Screenshot 2022-04-26 at 18 23 15" src="https://user-images.githubusercontent.com/825430/165347732-997f82b1-c96d-455a-a525-32e562c80adc.png">

The error is muted and not propagated to the k6 code.

**Exploring Possible solutions**

1 . Review golang kubernetes client to identify these errors
2. Create an API to check the job was successfully completed given a timeout.

**Comment by pablochacin** [comment]
@ppcano I will work on this issue following the idea suggested by @javaducky of adding an optional desired state and wait for it until a given timeout.
