### ISSUE TITLE
Error authenticating to cloud (GCP)

### ISSUE THREAD

**Issue by vincent-grafana** [grafana/xk6-kubernetes#50]
While running the basic list-pods script against a cluster in GCP, I encounter the following error:

```
ERRO[0000] no Auth Provider found for name "gcp"
        at file:///home/vw/dev/k6/scripts/list-pods.js:5:21(4)
        at native  executor=per-vu-iterations scenario=default source=stacktrace
```
From my understanding, the expected action is to read from the kubeconfig filepath provided (or take from the default path). 

Is the default incorrect, or does the documentation need to be updated differently?

**Comment by dgzlopes** [comment]
Did you change the script? Where is that `no Auth Provider found for name "gcp"` coming from? :eyes: 

Yeah, the client, once it's created, should fetch the kubeconfig from the default path, or the one provided.

**Comment by vincent-grafana** [comment]
Thanks - sounds like we need to include the auth module?

Simliar to:
https://github.com/kubernetes/client-go/blob/e121606b0d09b2e1c467183ee46217fa85a6b672/kubernetes/clientset.go#L35-Lundefined
